site_name: Coral Credits
repo_url: https://stackhpc.github.io/coral-credits
copyright: Copyright &copy; StackHPC 2024
edit_uri: ''

nav:
  - Home: index.md
  - Mission:
      - mission/index.md

theme:
  name: readthedocs
