site_name: Coral Credits
repo_url: https://stackhpc.github.io/coral-credits
copyright: Copyright &copy; StackHPC 2024
edit_uri: ''

nav:
  - Home: index.md
  - Mission:
      - mission/index.md
  - API Reference: api.md

theme:
  name: readthedocs

plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "docs.hooks:generate_schema"

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

# Configuration for API documentation
extra:
  schema_file: schema.yml