apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "coral-credits.fullname" . }}
  labels: {{ include "coral-credits.labels" . | nindent 4 }}
rules: 
  - apiGroups: [""]
    resources:
      - configmaps
      - persistentvolumeclaims
      - pods
      - pods/log
      - secrets
    verbs: ["*"]