---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "coral-credits.fullname" . }}
  labels: {{ include "coral-credits.labels" . | nindent 4 }}
spec:
  accessModes: {{ toYaml .Values.persistence.accessMode | nindent 4 }}
  {{- with .Values.persistence.storageClass }}
  {{- if (eq "-" .) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ . }}
  {{- end }}
  {{- end }}
  {{- with .Values.persistence.volumeBindingMode }}
  volumeBindingMode: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with .Values.persistence.selector }}
  selector: {{ toYaml . | nindent 4 }}
  {{- end -}}
  {{- with .Values.persistence.volumeName }}
  volumeName: {{ . }}
  {{- end -}}