apiVersion: v1
kind: Service
metadata:
  name: {{ include "coral-credits.fullname" . }}
  labels: {{ include "coral-credits.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.prometheusExporter.port }}
      targetPort: metrics
      protocol: TCP
  selector: {{ include "coral-credits.selectorLabels" . | nindent 6 }}