apiVersion: v2
name: coral-credits
description: Helm chart for deploying the Coral Credits API.
type: application
# The version and appVersion are set by the CI script
version: 0.1.0
appVersion: "main"